INFO:     Will watch for changes in these directories: ['/home/m4ck-y/Documents/me/FormFlow/backend2']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [382129] using StatReload
DEBUG:  True
[32mINFO[0m:database/model/question.py:<module> - Questions_form:  form_questions_form
[32mINFO[0m:database/model/question.py:<module> - Questions_section: form_questions_section
[32mINFO[0m:database/model/question.py:<module> - ModelQuestion: form_question
[32mINFO[0m:database/model/form.py:<module> - ModelForm initialized: form
app/config/init_db.py
init >>> db ... 
init >>> form ... 
init >>> section ... 
init >>> question ... 
2025-08-19 16:35:03,128 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-08-19 16:35:03,129 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,129 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,129 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,130 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,130 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,130 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,130 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,130 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,131 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("form_url")
2025-08-19 16:35:03,131 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,131 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("form_url")
2025-08-19 16:35:03,131 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,132 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,132 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,132 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,133 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,133 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,133 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,133 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,133 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,134 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,134 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,134 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,134 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,134 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,135 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,135 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,135 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,135 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,135 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,136 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,136 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,136 INFO sqlalchemy.engine.Engine PRAGMA database_list
2025-08-19 16:35:03,136 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-08-19 16:35:03,136 INFO sqlalchemy.engine.Engine ROLLBACK
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/m4ck-y/.local/share/uv/python/cpython-3.13.6-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/home/m4ck-y/.local/share/uv/python/cpython-3.13.6-linux-x86_64-gnu/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4ck-y/.local/share/uv/python/cpython-3.13.6-linux-x86_64-gnu/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/home/m4ck-y/.local/share/uv/python/cpython-3.13.6-linux-x86_64-gnu/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/m4ck-y/.local/share/uv/python/cpython-3.13.6-linux-x86_64-gnu/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/m4ck-y/.local/share/uv/python/cpython-3.13.6-linux-x86_64-gnu/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/app/main.py", line 27, in <module>
    init_db()
    ~~~~~~~^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/app/config/init_db.py", line 17, in init_db
    Base.metadata.create_all(bind=engine)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 5924, in create_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3252, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2459, in _run_ddl_visitor
    ).traverse_single(element)
      ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/sql/visitors.py", line 661, in traverse_single
    return meth(obj, **kw)
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 962, in visit_metadata
    collection = sort_tables_and_constraints(
        [t for t in tables if self._can_create_table(t)]
    )
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/sql/ddl.py", line 1394, in sort_tables_and_constraints
    dependent_on = fkc.referred_table
                   ^^^^^^^^^^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 4799, in referred_table
    return self.elements[0].column.table
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 1226, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ~~~~~~~~~^^^^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 3199, in column
    return self._resolve_column()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/m4ck-y/Documents/me/FormFlow/backend2/.venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 3222, in _resolve_column
    raise exc.NoReferencedTableError(
    ...<5 lines>...
    )
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'form_questions_form.id_form' could not find table 'form' with which to generate a foreign key to target column 'id'
INFO:     Stopping reloader process [382129]
